# Generated by Django 3.1.7 on 2021-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_travelled', models.IntegerField()),
                ('time', models.IntegerField()),
                ('kcal_burned', models.IntegerField()),
                ('avg_heart_beat', models.IntegerField()),
            ],
        ),
    ]
