# Generated by Django 3.1.7 on 2021-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='distance_travelled',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
